# Tic Tac Toe

In [1]:
import re
import numpy as np

## Exercise 24: Draw a game Board

In [9]:
def draw_board(rows,columns):
    for row in range(0,rows):
        for i in range(0,columns):
            print(' ---', end = '')
        print('')
        for i in range(0,columns+1):
            print('|   ', end = '')
        print('')
    for i in range(0,columns):
        print(' ---', end = '')
    return

In [10]:
size = input('What size do you want the Game Board to have? Please type in format _x_, e.g. 3x3, 5x7 (columns must be < 30): ')
if re.match('^[0-9]+[x][0-9]+$', size):
    size = size.split('x')
    row_nr = int(size[0])
    column_nr = int(size[1])
    if column_nr >= 30 or row_nr == 0 or column_nr == 0:
        if row_nr == 0 or column_nr == 0:
            print('0 is not a valid number')
        else:
            print('columns must be < 30')
    else:
        draw_board(row_nr,column_nr)
else:
    print('the format you entered is not correct')

What size do you want the Game Board to have? Please type in format _x_, e.g. 3x3, 5x7 (columns must be < 30): 4x4
 --- --- --- ---
|   |   |   |   |   
 --- --- --- ---
|   |   |   |   |   
 --- --- --- ---
|   |   |   |   |   
 --- --- --- ---
|   |   |   |   |   
 --- --- --- ---

## Exercise 26: Check Tic Tac Toe

### two ways of generating random lists:

In [52]:
testlist = np.random.randint(0,3,(3,3))
print(testlist)

[[0 1 1]
 [1 1 1]
 [2 2 1]]


In [7]:
#import random as rd
#testlist2 = [[] for i in range(0,3)]
#i=0
#while i < 3:
#    testlist2[i].append([rd.randint(0,2) for j in range(0,3)])
#    i+=1
#print(testlist2)

### checking for equals:

In [83]:
def checkrows(alist):
    testeq = False
    for i,exlist in enumerate(alist):
        testeq = all(element == exlist[0] for element in exlist)
        player = exlist[0]
        if testeq:
            break
    return testeq,i,exlist,player

In [22]:
def checkdiago(alist):
    templist = []
    for i,row in enumerate(alist):
        if i > len(alist[0])-1:
            break
        templist.append(row[i])
    testeq = all(element == templist[0] for element in templist)
    player = templist[0]
    return testeq,templist,player

In [53]:
checkrow = checkrows(testlist)
if checkrow[0]:
    if checkrow[3] == 0:
        print('no player has a row. Row', checkrow[1],'is an empty row.')
    else:
        print('all equal in row ', checkrow[1], '(',checkrow[2],'). Player', checkrow[3],'won.')
else:
    print('there`s no row where all elements are equal')

all equal in row  1 ( [1 1 1] ). Player 1 won.


In [26]:
transp_list = testlist.transpose()
checkcolumns = checkrows(transp_list)
if checkcolumns[0]:
    if checkcolumns[3] == 0:
        print('no player has a column. Column', checkcolumns[1],'is an empty column.') 
    else:
        print('all equal in column ', checkcolumns[1], '(',checkcolumns[2],'). Player', checkcolumns[3],'won.')
else:
    print('there`s no column where all elements are equal')

all equal in column  1 ( [2 2 2] ). Player 2 won.


In [27]:
diago = checkdiago(testlist)
if diago[0]:
    if diago[2] == 0:
        print('no player has the first diagonal.')
    else:
        print('all equal in the first diagonal (',diago[1],'). Player',diago[2],'won.')
else:
    print('In the first diagonal not all elements are equal')

In the first diagonal not all elements are equal


In [28]:
diago2 = checkdiago(testlist[::-1])
if diago2[0]:
    if diago2[2] == 0:
        print('no player has the second diagonal.')
    else:
        print('all equal in the second diagonal (',diago2[1],'). Player',diago2[2],'won.')
else:
    print('In the second diagonal not all elements are equal')

all equal in the second diagonal ( [2, 2, 2] ). Player 2 won.


## Exercise 27: Tic Tac Toe Draw

In [2]:
def playerdraw(playernr,boardstate,nr_rows,nr_cols):
    entry = True
    gameover = False
    if playernr == 1:
        sign = 'x'
    else:
        sign = 'o'
    print('')
    draw = input('Player %s, make your move! Please enter the coordinates in format _,_'
                '(if you want to leave the game, type "exit"): '%playernr)
    if re.match('^[0-9]+,[0-9]+|exit$', draw):
        if draw == 'exit':
            gameover = True
        else:
            [ro_draw,co_draw] = draw.split(',')
            ro_draw = int(ro_draw)-1
            co_draw = int(co_draw)-1
            if ro_draw > nr_rows-1 or co_draw > nr_cols-1 or ro_draw == -1 or co_draw == -1:
                if ro_draw > nr_rows-1 or co_draw > nr_cols-1:
                    print('This entry exceeds the board dimensions. Try again!')
                else:
                    print('0 is not a valid number')
                entry = False
            else:
                if boardstate[ro_draw][co_draw] == 0:
                    boardstate[ro_draw][co_draw] = sign
                else:
                    print('this position is already taken!')
                    entry = False
    else:
        print('The format you entered is not correct')
        entry = False
    return(boardstate,entry,gameover)

In [58]:
x = 3
y = 3
board = np.zeros((x,y),int)
print(board)
board = board.tolist()

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [60]:
i=1
while i <= x*y:
    if i%2 != 0:
        [board,player_entry,end] = playerdraw(1,board,x,y)
    else:
        [board,player_entry,end] = playerdraw(2,board,x,y)
    if end:
        print('You aborted the game. See ya!')
        break
    for row in board:
        print (*row, sep =', ') 
    #print(i,player_entry)
    if player_entry == True:
        i+=1


Player 1, make your move! Please enter the coordinates in format _,_(if you want to leave the game, type "exit"): exit
You aborted the game. See ya!


## Exercise 29. (Final) Tic Tac Toe Game

In [1]:
import re
import numpy as np

In [20]:
# Modified function from Exercise 24:

def draw_board2(rows,columns,boardlist):
    for row in range(0,rows):
        for i in range(0,columns):
            print(' ---', end = '')
        print('')
        for i in range(0,columns):
            if boardlist[row][i] == 0:
                print('|   ', end = '')
            elif boardlist[row][i] == 'x':
                print('| x ', end = '')
            elif boardlist[row][i] == 'o':
                print('| o ', end = '')
        print('|', end = '')
        print('')
    for i in range(0,columns):
        print(' ---', end = '')
    return


# the check-for-winner functions had to be adapted as the board now consists of 'x' and 'o' instead of 1 & 2.
def checkrows2(alist):
    testeq = False
    for i,exlist in enumerate(alist):
        testeq = all(element == exlist[0] for element in exlist)
        if exlist[0] == 'x':
            player = 1
        else:
            player = 2
        if testeq and exlist[0] != '0' and exlist[0] != 0:
            break
        else:
            testeq = False
    return testeq,i,exlist,player

def checkdiago2(alist):
    templist = []
    for i,row in enumerate(alist):
        if i > len(alist[0])-1:
            break
        templist.append(row[i])
    testeq = all(element == templist[0] for element in templist)
    if templist[0] == 'x':
        player = 1
    else:
        player = 2
    if templist[0] == 0:
        testeq = False
    return testeq,templist,player

In [21]:
# 1. Draw Game Board
Flag = True
size = input('What size do you want the Game Board to have? Please type in format _x_, e.g. 3x3, 5x7 (columns must be < 30): ')
if re.match('^[0-9]+[x][0-9]+$', size):
    size = size.split('x')
    row_nr = int(size[0])
    column_nr = int(size[1])
    if column_nr >= 30 or row_nr == 0 or column_nr == 0:
        if row_nr == 0 or column_nr == 0:
            print('0 is not a valid number')
            Flag = False
        else:
            print('columns must be < 30')
            Flag = False
    else:
        board = np.zeros((row_nr,column_nr),int)
        board = board.tolist()
        draw_board2(row_nr,column_nr,board)
else:
    print('the format you entered is not correct')
    Flag = False


# 2. Player Draw & Checking
if Flag:
    i=1
    while i <= row_nr*column_nr:
        if i%2 != 0:
            [board,player_entry,end] = playerdraw(1,board,row_nr,column_nr)
        else:
            [board,player_entry,end] = playerdraw(2,board,row_nr,column_nr)
        if end:
            print('You aborted the game. See ya!')
            break
        draw_board2(row_nr,column_nr,board)
        
        #check here for winner:
        checkrow = checkrows2(board)
        if checkrow[0]:
            print('')
            print('All equal in row ', checkrow[1]+1, '(',*checkrow[2],'). Congratulations Player',checkrow[3],
                    ', you have won!', sep = ' ')
            break
        board_array = np.array(board)
        transp_list = board_array.transpose()
        checkcolumns = checkrows2(transp_list)
        if checkcolumns[0]:
            print('')
            print('All equal in column ', checkcolumns[1]+1, '(',*checkcolumns[2],'). Congratulations Player',checkcolumns[3],
                    ', you have won!', sep = ' ')
            break
        diago = checkdiago2(board)
        if diago[0]:
            print('')
            print('All equal in the first diagonal (',*diago[1],'). Congratulations Player',diago[2],
                    ', you have won!', sep = ' ')
            break
        diago2 = checkdiago2(board[::-1])
        if diago2[0]:
            print('')
            print('All equal in the second diagonal (',*diago2[1],'). Congratulations Player',diago2[2],
                      ', you have won!', sep = ' ')     
            break
        if player_entry == True:
            i+=1
        if i == row_nr*column_nr:
            print('')
            print('Draw!')

What size do you want the Game Board to have? Please type in format _x_, e.g. 3x3, 5x7 (columns must be < 30): 29x2
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
Player 1, make your move! Please enter the coordinates in format _,_(if you want to leave the game, type "exit"): 1,1
 --- ---
| x |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |   |
 --- ---
|   |  